name: Docker Image CI

on: [push]

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['8', '10', '12']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Dockerize
      if: success()
      uses: manusa/actions-publish-docker@master
      with:
       name: organization/image_name
       username: ${{ secrets.DOCKER_HUB_USER }}
       password: ${{ secrets.DOCKER_HUB_PASSWORD }}
       tag script: |
        return context.ref
          .replace('refs/heads/
          .replace('refs/tags/'
          .replace('refs/pull/'
          .replace(/\//g, '_')
          .replace(/#/g, '');
       registry: localhost:8080

